//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication8_2_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_product
    {
        public int Orders_product_ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> Orders_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
